# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        MainWindow.setMinimumSize(QtCore.QSize(450, 600))
        MainWindow.setMaximumSize(QtCore.QSize(450, 600))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(200, 10, 129, 16))
        self.title.setObjectName("label_0")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 55, 16))
        self.label.setObjectName("label")


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 55, 16))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 55, 16))
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 250, 55, 16))
        self.label_4.setObjectName("label_4")


        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 40, 261, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight)


        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 90, 261, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight)


        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 150, 261, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight)


        #radio buttons
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(150, 250, 61, 31))
        self.radioButton.setObjectName("radioButton")

        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(250, 250, 61, 31))
        self.radioButton_2.setObjectName("radioButton_2")

        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(340, 250, 61, 31))
        self.radioButton_3.setObjectName("radioButton_3")


        self.print_label = QtWidgets.QLabel(self.centralwidget)
        self.print_label.setGeometry(QtCore.QRect(50, 400, 361, 81))
        self.print_label.setObjectName("print_label")

        #buttons
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 520, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.submit_button_pushed)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 520, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.clear_button_pushed)


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test 10"))
        self.title.setText(_translate("MainWindow", f"BILL CALCULATOR"))
        self.label.setText(_translate("MainWindow", "Food"))
        self.label_2.setText(_translate("MainWindow", "Drink"))
        self.label_3.setText(_translate("MainWindow", "Dessert"))
        self.label_4.setText(_translate("MainWindow", "Tip"))
        self.radioButton.setText(_translate("MainWindow", "10%"))
        self.radioButton.setChecked(True)
        self.radioButton_2.setText(_translate("MainWindow", "15%"))
        self.radioButton_3.setText(_translate("MainWindow", "20%"))
        self.pushButton.setText(_translate("MainWindow", "SUBMIT"))
        self.pushButton_2.setText(_translate("MainWindow", "CLEAR"))




    def submit_button_pushed(self):

        try:
            food = float(self.lineEdit.text())
            drink = float(self.lineEdit_2.text())
            dessert = float(self.lineEdit_3.text())

            if self.radioButton.isChecked():
                tip_selected = .10
            if self.radioButton_2.isChecked():
                tip_selected = .15
            if self.radioButton_3.isChecked():
                tip_selected = .20

            subTotal = food + drink + dessert
            tax = subTotal * .1
            tip = tip_selected *  (subTotal + tax)
            total = tip + tax + subTotal

            self.print_label.resize(140, 140)
            self.print_label.move(180,300)

            self.print_label.setAlignment(QtCore.Qt.AlignCenter)
            self.print_label.setText(f'Summary\n'
                                     f'Food:                {food:.2f} \n '
                                     f'Drink:               {drink:.2f}\n'
                                     f'Dessert:             {dessert:.2f}\n'
                                     f'Tax                  {tax:.2f}\n'
                                     f'Tip:                 {tip:.2f}\n\n'
                                     f'Total:               {total:.2f}')





        except ValueError:
            self.print_label.resize(140, 140)
            self.print_label.move(180, 300)
            self.print_label.setAlignment(QtCore.Qt.AlignLeft)
            self.print_label.setText(f'Food. drink. and dessert\n '
                                     f'need to be numeric\n'
                                     f' e.g. 10.25 not $10.25')



    def clear_button_pushed(self):
        self.lineEdit.setText(' ')
        self.lineEdit_2.setText(' ')
        self.lineEdit_3.setText(' ')
        self.radioButton.setChecked(True)
        self.print_label.setText(' ')